// ========================================
// i18n - Bilingual Support (ZH default)
// ========================================
const I18N = {
    zh: {
        title: '🏠 3D室内场景生成质量评估',
        instructions_title: '研究说明',
        instructions_intro: '感谢您参与本次用户研究！本研究旨在评估不同AI方法生成的3D室内场景的质量。',
        warning_title: '⚠️ 重要提示',
        warning_text: '请在做排名决定之前仔细阅读提示文本！',
        warning_sub: '提示描述了预期的房间设计，请考虑每种方法对提示要求的满足程度。',
        task_title: '📋 任务概述',
        task_desc: '您将评估 <strong>5个场景</strong>，每个场景包含6种不同方法生成的结果。',
        task_sub: '对于每个场景，您需要完成两项排名任务：',
        task_item1: '<strong>物理合理性排名</strong>：检查物体重叠或越界问题',
        task_item2: '<strong>视觉质量排名</strong>：考虑场景合理性、布局美观性和可达性',
        criteria_title: '📊 评估标准',
        physics_title: '物理合理性',
        physics_1: '物体重叠 / 碰撞',
        physics_2: '物体超出房间边界',
        physics_3: '悬浮物体',
        visual_title: '视觉质量',
        visual_1: '<strong>合理性 (Ra.)：</strong>适当的房间大小、合理的物体数量、良好的物理合理性，以及包含该房间类型的关键物体',
        visual_2: '<strong>空间布局 (Spa.)：</strong>合理的功能分区和良好的空间分布平衡。物体过度聚集或存在大片空白区域的房间被认为布局较差',
        visual_3: '<strong>可达性 (Ac.)：</strong>所有物体应可到达和触及，物体之间有足够的行走空间供人移动。过度拥挤导致物体无法到达是不可接受的',
        time_title: '⏱️ 预计时间',
        time_desc: '整个评估过程大约需要 <strong>5-10分钟</strong>。',
        start_btn: '开始评估',
        prompt_label: '提示词：',
        criteria_btn: '📊 查看评估标准',
        physics_title2: '🔧 物理合理性',
        physics_c1: '<strong>重叠：</strong>物体是否相互穿插？',
        physics_c2: '<strong>边界：</strong>物体是否在房间内？',
        physics_c3: '<strong>悬浮：</strong>物体是否落地？',
        visual_title2: '🎨 视觉质量',
        visual_c1: '<strong>合理性 (Ra.)：</strong>适当的房间大小、合理的物体数量、良好的物理合理性，以及包含该房间类型的关键物体',
        visual_c2: '<strong>空间布局 (Spa.)：</strong>合理的功能分区和良好的空间分布平衡。物体过度聚集或存在大片空白区域的房间被认为布局较差',
        visual_c3: '<strong>可达性 (Ac.)：</strong>所有物体应可到达和触及，物体之间有足够的行走空间供人移动。过度拥挤导致物体无法到达是不可接受的',
        scene_preview: '场景预览（点击放大）',
        physics_rank_title: '🔧 物理合理性排名',
        rank_hint: '拖动排序：最好(1) 到 最差(6)',
        visual_rank_title: '🎨 视觉质量排名',
        rank_hint2: '拖动排序：最好(1) 到 最差(6)',
        prev_btn: '上一题',
        next_btn: '下一题',
        submit_btn: '提交',
        thanks_title: '🎉 感谢您的参与！',
        thanks_desc: '您的评估结果已成功提交。',
        submitting: '提交数据中...',
        summary_title: '评估摘要',
        img_load_fail: '图片加载失败',
        img_retry: '点击重试',
        submit_success: '✅ 数据提交成功！',
        submit_no_url: '⚠️ 服务器未配置，请手动保存以下数据：',
        submit_fail: '❌ 提交失败，请手动保存以下数据：',
        copy_btn: '复制到剪贴板',
        copied: '已复制到剪贴板！',
        summary_thanks: '感谢您的评估！您的排名已记录。',
        lang_toggle: 'English',
    },
    en: {
        title: '🏠 3D Indoor Scene Generation Quality Assessment',
        instructions_title: 'Study Instructions',
        instructions_intro: 'Thank you for participating in this user study! This research aims to evaluate the quality of 3D indoor scenes generated by different AI methods.',
        warning_title: '⚠️ Important Reminder',
        warning_text: 'Please carefully read the prompt text before making your ranking decisions!',
        warning_sub: 'The prompt describes the intended room design. Consider how well each method fulfills the prompt requirements.',
        task_title: '📋 Task Overview',
        task_desc: 'You will evaluate <strong>5 scenes</strong>, each containing results generated by 6 different methods.',
        task_sub: 'For each scene, you need to complete two ranking tasks:',
        task_item1: '<strong>Physical Plausibility Ranking</strong>: Check for object overlap or out-of-bounds issues',
        task_item2: '<strong>Visual Quality Ranking</strong>: Consider scene reasonableness, layout aesthetics, and accessibility',
        criteria_title: '📊 Evaluation Criteria',
        physics_title: 'Physical Plausibility',
        physics_1: 'Object overlap / collision',
        physics_2: 'Objects out of room bounds',
        physics_3: 'Floating objects',
        visual_title: 'Visual Quality',
        visual_1: '<strong>Rationality (Ra.):</strong> Appropriate room size, reasonable number of objects, good physical plausibility, and contains key objects for the room type',
        visual_2: '<strong>Spatial Layout (Spa.):</strong> Reasonable functional zoning and good spatial distribution balance.',
        visual_3: '<strong>Accessibility (Ac.):</strong> All objects should be reachable and touchable, with sufficient walking space between objects.',
        time_title: '⏱️ Estimated Time',
        time_desc: 'The entire evaluation process takes approximately <strong>5-10 minutes</strong>.',
        start_btn: 'Start Evaluation',
        prompt_label: 'Prompt:',
        criteria_btn: '📊 View Evaluation Criteria',
        physics_title2: '🔧 Physical Plausibility',
        physics_c1: '<strong>Overlap:</strong> Are objects intersecting?',
        physics_c2: '<strong>Bounds:</strong> Are objects within room?',
        physics_c3: '<strong>Floating:</strong> Are objects grounded?',
        visual_title2: '🎨 Visual Quality',
        visual_c1: '<strong>Rationality (Ra.):</strong> Appropriate room size, reasonable number of objects, good physical plausibility, and contains key objects for the room type',
        visual_c2: '<strong>Spatial Layout (Spa.):</strong> Reasonable functional zoning and good spatial distribution balance.',
        visual_c3: '<strong>Accessibility (Ac.):</strong> All objects should be reachable and touchable, with sufficient walking space.',
        scene_preview: 'Scene Preview (Click to enlarge)',
        physics_rank_title: '🔧 Physical Plausibility Ranking',
        rank_hint: 'Drag to rank: Best (1) to Worst (6)',
        visual_rank_title: '🎨 Visual Quality Ranking',
        rank_hint2: 'Drag to rank: Best (1) to Worst (6)',
        prev_btn: 'Previous',
        next_btn: 'Next',
        submit_btn: 'Submit',
        thanks_title: '🎉 Thank You for Participating!',
        thanks_desc: 'Your evaluation results have been successfully submitted.',
        submitting: 'Submitting data...',
        summary_title: 'Evaluation Summary',
        img_load_fail: 'Image Loading Failed',
        img_retry: 'Click to retry',
        submit_success: '✅ Data successfully submitted!',
        submit_no_url: '⚠️ Server not configured. Please save the following data manually:',
        submit_fail: '❌ Submission failed. Please save the following data manually:',
        copy_btn: 'Copy to Clipboard',
        copied: 'Copied to clipboard!',
        summary_thanks: 'Thank you for your evaluation! Your rankings have been recorded.',
        lang_toggle: '中文',
    }
};

let currentLang = 'zh';
function t(key) { return (I18N[currentLang][key] !== undefined) ? I18N[currentLang][key] : key; }

function applyI18n() {
    document.querySelectorAll('[data-i18n]').forEach(function(el) {
        var key = el.getAttribute('data-i18n');
        var val = t(key);
        if (val !== undefined) el.innerHTML = val;
    });
    var btn = document.getElementById('lang-toggle-btn');
    if (btn) btn.textContent = t('lang_toggle');
    updateNavigationButtons();
}

function toggleLanguage() {
    currentLang = currentLang === 'zh' ? 'en' : 'zh';
    document.documentElement.lang = currentLang;
    applyI18n();
    if (document.getElementById('evaluation-page').classList.contains('active')) {
        loadCurrentPrompt();
    }
}

// ========================================
// Global State
// ========================================
let state = {
    sessionId: generateSessionId(),
    selectedPrompts: [],
    currentIndex: 0,
    results: [],
    startTime: null
};

function generateSessionId() {
    return 'user_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
}

function shuffleArray(array) {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}

function generateAllPrompts() {
    const prompts = [];
    for (const [sceneType, promptIds] of Object.entries(SCENE_CONFIG.prompts)) {
        for (const promptId of promptIds) {
            prompts.push({ sceneType, promptId, displayName: SCENE_CONFIG.sceneTypes[sceneType] });
        }
    }
    return prompts;
}

function getImagePath(sceneType, promptId, method) {
    const key = sceneType + '/' + promptId;
    if (SCENE_CONFIG.specialFileNames && SCENE_CONFIG.specialFileNames[key] && SCENE_CONFIG.specialFileNames[key][method]) {
        return SCENE_CONFIG.imageBasePath + sceneType + '/' + promptId + '/' + SCENE_CONFIG.specialFileNames[key][method];
    }
    return SCENE_CONFIG.imageBasePath + sceneType + '/' + promptId + '/' + SCENE_CONFIG.defaultFileNames[method];
}

document.addEventListener('DOMContentLoaded', function() {
    document.getElementById('start-btn').addEventListener('click', startEvaluation);
    document.getElementById('prev-btn').addEventListener('click', previousPrompt);
    document.getElementById('next-btn').addEventListener('click', nextPrompt);
    document.querySelector('.close-modal').addEventListener('click', closeModal);
    document.getElementById('image-modal').addEventListener('click', function(e) { if (e.target === this) closeModal(); });
    document.addEventListener('keydown', function(e) { if (e.key === 'Escape') closeModal(); });
    document.getElementById('lang-toggle-btn').addEventListener('click', toggleLanguage);
    applyI18n();
});

function startEvaluation() {
    state.startTime = new Date();
    const allPrompts = generateAllPrompts();
    state.selectedPrompts = shuffleArray(allPrompts).slice(0, SCENE_CONFIG.promptsPerSession);
    state.results = state.selectedPrompts.map(prompt => {
        const shuffledMethods = shuffleArray([...SCENE_CONFIG.methodKeys]);
        const labelToMethod = {};
        SCENE_CONFIG.methodLabels.forEach((label, index) => { labelToMethod[label] = shuffledMethods[index]; });
        return { sceneType: prompt.sceneType, promptId: prompt.promptId, physicsRanking: null, visualRanking: null, labelToMethod };
    });
    showPage('evaluation-page');
    setupCriteriaToggle();
    loadCurrentPrompt();
}

function setupCriteriaToggle() {
    const toggleBtn = document.getElementById('criteria-toggle');
    const content = document.getElementById('criteria-content');
    if (toggleBtn && content) {
        const newBtn = toggleBtn.cloneNode(true);
        toggleBtn.parentNode.replaceChild(newBtn, toggleBtn);
        newBtn.addEventListener('click', function() {
            newBtn.classList.toggle('active');
            content.classList.toggle('active');
        });
    }
}

function showPage(pageId) {
    document.querySelectorAll('.page').forEach(p => p.classList.remove('active'));
    document.getElementById(pageId).classList.add('active');
    applyI18n();
}

function loadCurrentPrompt() {
    const current = state.selectedPrompts[state.currentIndex];
    const result = state.results[state.currentIndex];
    const progress = ((state.currentIndex + 1) / state.selectedPrompts.length) * 100;
    document.getElementById('progress-fill').style.width = progress + '%';
    document.getElementById('progress-text').textContent = (state.currentIndex + 1) + ' / ' + state.selectedPrompts.length;
    document.getElementById('scene-type').textContent = current.displayName;
    const promptKey = current.sceneType + '/' + current.promptId;
    document.getElementById('prompt-text').textContent = SCENE_CONFIG.promptTexts[promptKey] || 'Prompt not available';
    loadImages(current, result);
    loadRankingLists(result);
    updateNavigationButtons();
}

function loadImages(prompt, result) {
    const grid = document.getElementById('images-grid');
    grid.innerHTML = '';
    SCENE_CONFIG.methodLabels.forEach(methodLabel => {
        const method = result.labelToMethod[methodLabel];
        const card = document.createElement('div');
        card.className = 'image-card loading';
        const imgPath = getImagePath(prompt.sceneType, prompt.promptId, method);
        const img = document.createElement('img');
        img.alt = methodLabel;
        img.loading = 'lazy';
        img.onload = () => { card.classList.remove('loading'); card.classList.add('loaded'); };
        img.onerror = function() {
            card.classList.remove('loading'); card.classList.add('error');
            if (!this.dataset.retried) {
                this.dataset.retried = 'true';
                setTimeout(() => { img.src = imgPath + '?t=' + Date.now(); }, 1000);
            } else {
                this.src = 'data:image/svg+xml,' + encodeURIComponent(
                    '<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300"><rect fill="#f0f0f0" width="400" height="300"/>' +
                    '<text x="200" y="150" text-anchor="middle" fill="#999" font-size="16">' + t('img_load_fail') + '</text></svg>'
                );
            }
        };
        img.src = imgPath;
        const labelDiv = document.createElement('div');
        labelDiv.className = 'method-label';
        labelDiv.textContent = methodLabel;
        card.appendChild(img);
        card.appendChild(labelDiv);
        card.addEventListener('click', function() {
            if (card.classList.contains('error')) {
                card.classList.remove('error'); card.classList.add('loading');
                img.dataset.retried = ''; img.src = imgPath + '?t=' + Date.now();
            } else { openModal(imgPath, methodLabel); }
        });
        grid.appendChild(card);
    });
}

function loadRankingLists(result) {
    const labels = [...SCENE_CONFIG.methodLabels];
    const methodToLabel = {};
    for (const [label, method] of Object.entries(result.labelToMethod)) { methodToLabel[method] = label; }
    const physicsLabels = result.physicsRanking ? result.physicsRanking.map(m => methodToLabel[m]) : [...labels];
    const visualLabels = result.visualRanking ? result.visualRanking.map(m => methodToLabel[m]) : [...labels];
    loadSortableList('physics-ranking', physicsLabels, result);
    loadSortableList('visual-ranking', visualLabels, result);
}

function loadSortableList(listId, labels, result) {
    const list = document.getElementById(listId);
    list.innerHTML = '';
    labels.forEach((label, index) => {
        const li = document.createElement('li');
        li.dataset.label = label;
        li.dataset.method = result.labelToMethod[label];
        li.innerHTML = '<span class="rank-number">' + (index + 1) + '</span>' +
            '<span class="method-name">' + label + '</span>' +
            '<span class="drag-handle">⋮⋮</span>';
        list.appendChild(li);
    });
    new Sortable(list, {
        animation: 150,
        ghostClass: 'sortable-ghost',
        chosenClass: 'sortable-chosen',
        onEnd: function() { updateRankNumbers(list); saveCurrentRanking(); }
    });
}

function updateRankNumbers(list) {
    list.querySelectorAll('li').forEach((item, index) => {
        item.querySelector('.rank-number').textContent = index + 1;
    });
}

function saveCurrentRanking() {
    const result = state.results[state.currentIndex];
    result.physicsRanking = Array.from(document.querySelectorAll('#physics-ranking li')).map(i => i.dataset.method);
    result.visualRanking = Array.from(document.querySelectorAll('#visual-ranking li')).map(i => i.dataset.method);
}

function updateNavigationButtons() {
    const prevBtn = document.getElementById('prev-btn');
    const nextBtn = document.getElementById('next-btn');
    if (!prevBtn || !nextBtn) return;
    prevBtn.disabled = state.currentIndex === 0;
    if (state.selectedPrompts.length > 0 && state.currentIndex === state.selectedPrompts.length - 1) {
        nextBtn.textContent = t('submit_btn');
    } else {
        nextBtn.textContent = t('next_btn');
    }
}

function previousPrompt() {
    if (state.currentIndex > 0) { saveCurrentRanking(); state.currentIndex--; loadCurrentPrompt(); }
}

function nextPrompt() {
    saveCurrentRanking();
    if (state.currentIndex < state.selectedPrompts.length - 1) { state.currentIndex++; loadCurrentPrompt(); }
    else { submitResults(); }
}

async function submitResults() {
    showPage('completion-page');
    const statusBox = document.getElementById('submission-status');
    statusBox.innerHTML = '<p>⏳ ' + t('submitting') + '</p>';
    statusBox.className = 'status-box';
    const submissionData = {
        sessionId: state.sessionId,
        timestamp: new Date().toISOString(),
        duration: Math.round((new Date() - state.startTime) / 1000),
        results: state.results.map(r => ({ sceneType: r.sceneType, promptId: r.promptId, physicsRanking: r.physicsRanking, visualRanking: r.visualRanking }))
    };
    try {
        if (GOOGLE_SCRIPT_URL && GOOGLE_SCRIPT_URL !== 'YOUR_GOOGLE_APPS_SCRIPT_URL_HERE') {
            await fetch(GOOGLE_SCRIPT_URL, { method: 'POST', mode: 'no-cors', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(submissionData) });
            statusBox.innerHTML = '<p>' + t('submit_success') + '</p>';
            statusBox.className = 'status-box success';
        } else {
            statusBox.innerHTML = '<p>' + t('submit_no_url') + '</p><textarea style="width:100%;height:150px;margin-top:10px;font-family:monospace;font-size:12px;">' + JSON.stringify(submissionData, null, 2) + '</textarea><button onclick="copyToClipboard()" style="margin-top:10px;padding:10px 20px;cursor:pointer;">' + t('copy_btn') + '</button>';
        }
    } catch(e) {
        statusBox.innerHTML = '<p>' + t('submit_fail') + '</p><textarea style="width:100%;height:150px;margin-top:10px;font-family:monospace;font-size:12px;">' + JSON.stringify(submissionData, null, 2) + '</textarea>';
        statusBox.className = 'status-box error';
    }
    showSummary();
}

function copyToClipboard() {
    const textarea = document.querySelector('#submission-status textarea');
    if (textarea) { textarea.select(); document.execCommand('copy'); alert(t('copied')); }
}

function showSummary() {
    const summaryContent = document.getElementById('summary-content');
    let html = '<table style="width:100%;border-collapse:collapse;"><tr style="background:#f0f0f0;"><th style="padding:10px;text-align:left;">Scene</th><th style="padding:10px;text-align:left;">Physics</th><th style="padding:10px;text-align:left;">Visual</th></tr>';
    state.results.forEach(result => {
        const methodToLabel = {};
        for (const [label, method] of Object.entries(result.labelToMethod)) { methodToLabel[method] = label; }
        html += '<tr style="border-bottom:1px solid #eee;"><td style="padding:10px;">' + SCENE_CONFIG.sceneTypes[result.sceneType] + '<br><small>' + result.promptId + '</small></td>' +
            '<td style="padding:10px;font-size:0.85em;">' + result.physicsRanking.map(m => methodToLabel[m]).join(' > ') + '</td>' +
            '<td style="padding:10px;font-size:0.85em;">' + result.visualRanking.map(m => methodToLabel[m]).join(' > ') + '</td></tr>';
    });
    html += '</table><p style="margin-top:20px;color:#666;font-style:italic;">' + t('summary_thanks') + '</p>';
    summaryContent.innerHTML = html;
}

function openModal(imgSrc, caption) {
    document.getElementById('modal-image').src = imgSrc;
    document.getElementById('modal-caption').textContent = caption;
    document.getElementById('image-modal').classList.add('active');
}

function closeModal() {
    document.getElementById('image-modal').classList.remove('active');
}
